name: Python

on:
  push:
    branches:
      - master
      - python*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  manylinux:
    name: Python
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_28_x86_64

    strategy:
      matrix:
        version: [ "3.6", "3.8", "3.10", "3.11", "3.12" ]

    env:
      PYTHON: python${{ matrix.version }}

    steps:
    - name: Install dependencies
      run: dnf install -y git krb5-devel libuuid-devel openssl-devel

    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build source distribution tarball
      run: ./genversion.sh >| VERSION && ${PYTHON} -m build --sdist

    - name: Build binary wheel
      run: ${PYTHON} -m pip wheel --use-pep517 --verbose dist/*.tar.gz

    - name: Install binary wheel
      run: ${PYTHON} -m pip install xrootd*.whl

    - name: Run post-installation tests
      run: |
        command -v ${PYTHON} && ${PYTHON} --version
        ${PYTHON} -m pip show xrootd
        ${PYTHON} -c 'import XRootD; print(XRootD)'
        ${PYTHON} -c 'import pyxrootd; print(pyxrootd)'
        ${PYTHON} -c 'from XRootD import client; help(client)'
        ${PYTHON} -c 'from XRootD import client; print(client.FileSystem("root://localhost"))'
