name: RPM

on:
  push:
    branches:
      - rpm
      - master
      - packaging

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  centos7:
    name: CentOS 7
    runs-on: ubuntu-latest
    container: centos:7

    steps:
    - name: Install git
      run: yum install -y git

    - name: Clone repository
      uses: actions/checkout@v1

    - name: Install RPM development tools
      run: |
        yum install -y centos-release-scl epel-release
        yum install -y epel-rpm-macros rpmdevtools yum-utils

    - name: Install XRootD build dependencies
      run: yum-builddep -y xrootd.spec

    - name: Build RPMs
      run: |
        rpmdev-setuptree
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git archive --prefix xrootd/ -o $(rpm -E '%{_sourcedir}')/xrootd.tar.gz HEAD
        rpmbuild -bb --with git xrootd.spec

    - name: Install RPMs
      run: yum install -y $(rpm -E '%{_rpmdir}')/*/*.rpm

    - name: Run post-install checks
      run: |
        command -v xrdcp
        xrdcp --version
        command -v xrootd
        xrootd -H
        python3 -m pip show xrootd
        python3 -c 'from XRootD import client; help(client)'
        python3 -c 'import XRootD; print(XRootD)'
        python3 -c 'import pyxrootd; print(pyxrootd)'
        python3 -c 'from XRootD import client; print(client.FileSystem("root://localhost"))'

  alma8:
    name: Alma Linux 8
    runs-on: ubuntu-latest
    container: almalinux:8

    steps:
    - name: Install git
      run: yum install -y git

    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install RPM development tools
      run: |
        dnf install -y epel-release rpmdevtools dnf-plugins-core
        dnf config-manager --set-enabled powertools

    - name: Install XRootD build dependencies
      run: dnf builddep -y xrootd.spec

    - name: Build RPMs
      run: |
        rpmdev-setuptree
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git archive --prefix xrootd/ -o $(rpm -E '%{_sourcedir}')/xrootd.tar.gz HEAD
        rpmbuild -bb --with git xrootd.spec

    - name: Install RPMs
      run: dnf install -y $(rpm -E '%{_rpmdir}')/*/*.rpm

    - name: Run post-install checks
      run: |
        command -v xrdcp && xrdcp --version
        command -v python3 && python3 --version
        python3 -m pip show xrootd
        python3 -c 'from XRootD import client; help(client)'
        python3 -c 'from pyxrootd import client; help(client)'
        python3 -c 'from XRootD import client; print(client.FileSystem("root://localhost"))'

  alma9:
    name: Alma Linux 9
    runs-on: ubuntu-latest
    container: almalinux:9

    steps:
    - name: Install git
      run: yum install -y git

    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install RPM development tools
      run: |
        dnf install -y epel-release rpmdevtools dnf-plugins-core
        dnf config-manager --set-enabled crb

    - name: Install XRootD build dependencies
      run: dnf builddep -y xrootd.spec

    - name: Build RPMs
      run: |
        rpmdev-setuptree
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git archive --prefix xrootd/ -o $(rpm -E '%{_sourcedir}')/xrootd.tar.gz HEAD
        rpmbuild -bb --with git xrootd.spec

    - name: Install RPMs
      run: dnf install -y $(rpm -E '%{_rpmdir}')/*/*.rpm

    - name: Run post-install checks
      run: |
        command -v xrdcp && xrdcp --version
        command -v python3 && python3 --version
        python3 -m pip show xrootd
        python3 -c 'from XRootD import client; help(client)'
        python3 -c 'from pyxrootd import client; help(client)'
        python3 -c 'from XRootD import client; print(client.FileSystem("root://localhost"))'

  fedora:
    name: Fedora 38
    runs-on: ubuntu-latest
    container: fedora:38

    steps:
    - name: Install git
      run: yum install -y git

    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install RPM development tools
      run: |
        dnf install -y rpmdevtools dnf-plugins-core

    - name: Install XRootD build dependencies
      run: dnf builddep -y --define 'with_ceph 1' xrootd.spec

    - name: Build RPMs
      run: |
        rpmdev-setuptree
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git archive --prefix xrootd/ -o $(rpm -E '%{_sourcedir}')/xrootd.tar.gz HEAD
        rpmbuild -bb --with git --with ceph xrootd.spec

    - name: Install RPMs
      run: dnf install -y $(rpm -E '%{_rpmdir}')/*/*.rpm

    - name: Run post-install checks
      run: |
        command -v xrdcp && xrdcp --version
        command -v python3 && python3 --version
        python3 -m pip show xrootd
        python3 -c 'from XRootD import client; help(client)'
        python3 -c 'from pyxrootd import client; help(client)'
        python3 -c 'from XRootD import client; print(client.FileSystem("root://localhost"))'
